apiVersion: apps/v1
kind: Deployment
metadata:
  name: tuer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tuer
  template:
    metadata:
      labels:
        app: tuer
    spec:
      containers:
      - image: okteto.dev/tuer:latest
        name: tuer
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "e61fb92d-29bc-4f29-80d6-5fffc9c96a98"
        - name: Vless_Path
          value: "/vl346gbt55"
        - name: Vmess_UUID
          value: "e61fb92d-29bc-4f29-80d6-5fffc9c96a98"
        - name: Vmess_Path
          value: "/vm6hbtrd6433fg6"
        - name: Share_Path
          value: "/v2link"
